version = 3.11.5
runner.dialect = scala3
align.preset = most
maxColumn = 250
assumeStandardLibraryStripMargin = true
align.stripMargin = true
indent.defnSite = 2

// keep brace-based Scala 2 style syntax: never rewrite to significant indentation
rewrite.scala3.removeOptionalBraces = no
rewrite.scala3.convertToNewSyntax = false

//align.tokens.add = [
//  {code = "=", owner = "Term.Arg.Named"}
//]
