/*
 * Copyright 2026 David Crosson
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package zio.lmdb

import scalapb.{GeneratedMessage, GeneratedMessageCompanion}
import java.nio.ByteBuffer

package object protobuf {

  /** Implicit codec for any ScalaPB generated message.
    *
    * This allows any class generated by ScalaPB to be automatically used as a value
    * in a ZIO LMDB collection.
    */
  implicit def protobufCodec[T <: GeneratedMessage](implicit cmp: GeneratedMessageCompanion[T]): LMDBCodec[T] =
    new LMDBCodec[T] {
      override def encode(value: T): Array[Byte] = value.toByteArray

      override def decode(valueBytes: ByteBuffer): Either[String, T] = {
        try {
          // Create a byte array from the ByteBuffer to parse
          val arr = new Array[Byte](valueBytes.remaining())
          valueBytes.get(arr)
          Right(cmp.parseFrom(arr))
        } catch {
          case e: Exception => Left(s"Failed to decode protobuf message: ${e.getMessage}")
        }
      }
    }
}
